### ISSUE TITLE
Listings possible?

### ISSUE THREAD

**Issue by ghost** [antonioortegajr/IDX-Broker-API-Quick-Tester#11]
Is it possible to get listing via the API rather then iframe links?

**Comment by antonioortegajr** [comment]
So the IDX Broker API doesn't return listing data other than listings belonging to the agent(s) on the account. You can not query all the MLS data via the API. Check out http://developers.idxbroker.com/ for more.

Additionally links given are not meant for iframes. IDX Broker is meant to be on a custom subdomain not an iframe.
